version: '3.7'

services:

  mongo-db:
    image: mongo:4.4
    ports: 
      - 27100:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoUser
      - MONGO_INITDB_ROOT_PASSWORD=mongoPassword
      - MONGO_INITDB_DATABASE=ORDER
      
  mongo-data:
    user: root
    image: mongo:4.4
    volumes:
        - ./MongoDB/data:/mongo-data
    command:
        sh -c "mongoimport --host mongo-db --port 27017 --db ORDER --authenticationDatabase admin --username mongoUser --password mongoPassword --collection Order --type json '/mongo-data/Order.json' && mongoimport --host mongo-db --port 27017 --db ORDER --authenticationDatabase admin --username mongoUser --password mongoPassword --collection Product --type csv --file '/mongo-data/Product.csv' --headerline && mongoimport --host mongo-db --port 27017 --db ORDER --authenticationDatabase admin --username mongoUser --password mongoPassword --collection BrandProduct --type csv --file '/mongo-data/BrandByProduct.csv' --fields vendor.string\(\),asin.string\(\) --columnsHaveTypes"
        
  mongo-express:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoUser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongoPassword
      - ME_CONFIG_MONGODB_SERVER=mongo-db
    ports:
      - 8081:8081
    depends_on:
      - mongo-db
    restart: unless-stopped
